services:
  be-user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: be-user-service
    restart: unless-stopped
    ports:
      - 3003:3003
    volumes:
      - .:/app
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
